### PR TITLE
doc: fix plugin example

### PR DESCRIPTION
**Pull request by joakim-brannstrom**

### CODE REVIEW

**Comment by joakim-brannstrom** [comment]
Updated after feedback on #362

**Comment by joakim-brannstrom** [comment]
@ploq You had some comments earlier in the project that deXtool was lacking documentation. I'm trying bit by bit to fix it.
I'll gladly take any feedback that you can provide :)

The example do not show how to use "representation.d" but... one thing at a time ;)

**Comment by ploq** [comment]
Hmm... Well I don't think that representation.d needs much documentation in the example plugin (not showing every statement etc.). It is quite self explanatory how it works if one would implement a for-loop, some statements and maybe some C++ stuff like templates. Basically some basic functionality about dsrcgen. 

Other than that, I think that the example plugin is good enough. :)

**Comment by joakim-brannstrom** [comment]
Thanks for the feedback :)
Updated with a bit more examples of using the analyze and dsrcgen.

**Pull request merged**
