### PR TITLE
mac support

### PR DESCRIPTION
**Pull request by ploq**
Seems to fail one test "test.component.analyzer.type.Should be a type of kind 'func'", unable to test on linux at the moment to see if the same test fails there too.

### CODE REVIEW

**Comment by joakim-brannstrom** [comment]
All pull requests are automatically ran by Travis-CI (linux).
You changes doesn't seem to affect that so good times man.

**Comment by joakim-brannstrom** [comment]
Hmm, I guess the test code is "linux specific".
Does it fail on line 109?
tip to only run the test specific test in debug mode (-h for more options):
```d
./build/unittest -d "test.component.analyzer.type.Should be a type of kind 'func'"
```

**Comment by ploq** [comment]
The tests fails to find clocale, which seems odd since that library exists in Apples version of Clang.

**Comment by joakim-brannstrom** [comment]
Ahh, cool. I guess ClangContext.makeTranslationUnit need an extra "-I" to find the system installation of standard headers.

But lets go with the version-block instead, for now. I don't have a Mac myself so wouldn't be able to fix future bugs either way.

**Comment by joakim-brannstrom** [comment]
Travis-CI is green. Do you feel it is ready to be merged?

**Comment by ploq** [comment]
autobuild does not work at the moment, it fails to find the environment variable `$DYLB_LIBRARY_PATH`, which makes unable to run dextool. Will see if I can figure something out for that

**Comment by joakim-brannstrom** [comment]
If you are wondering what dub is doing in the background you can tell it to be more verbose.
```d
dub build -c unittest -b unittest --verbose
```

**Comment by joakim-brannstrom** [comment]
or
```sh
readelf --dynamic ./build/dextool
```

One way may be to change the path that is searched for libclang.so (I guess it is this one that is the problem).
library path is set to [.] by -rpath in dub.sdl.
If you changed "-rpath" in dub.sdl to wherever it is in your system it should work.

**Comment by ploq** [comment]
Yes, correct, there is a problem with rpath. Problem is that when dmd is linking it says that ld does not have rpath as a option (it does).

**Comment by ploq** [comment]
If Travis-CI is green then everything should be working!

**Comment by joakim-brannstrom** [comment]
Awesome man. Will do!

**Pull request merged**
